### PR TITLE
XML cofing files for the OMTF displaced algo.

### PR DESCRIPTION
**Pull request by akalinow**
XML configuration files that will be used with an updated version of the OMTF emulator. The emulator code PR will follow this PR in a few  weeks.

### CODE REVIEW

**Comment by akalinow** [comment]
adding @mbluj @kbunkow as observers

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
@akalinow Was the PR that corresponds to this ever made/merged?

**Comment by aloeliger** [comment]
+l1

**Comment by akalinow** [comment]
Yes, the corresponding PR to CMSSW are  [43687](https://github.com/cms-sw/cmssw/pull/43687)  [1196](https://github.com/cms-l1t-offline/cmssw/pull/1196)

**Comment by aloeliger** [comment]
Okay, perfect, thanks.

**Comment by smuzaffar** [comment]
+externals

only new data files but this should be merged along with https://github.com/cms-sw/cmssw/pull/43687

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
ping bot

**Pull request merged**
