### PR TITLE
Data file update for EMTF NN

### PR DESCRIPTION
**Pull request by eyigitba**
Data for EMTF NN for displaced muons.

Updated the EMTF NN version to match the version implemented in firmware at P5

Will be needed for a PR to 12_4_X, and a backport to 12_3_X

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1
- Needed by #37825, and tested together with it

**Comment by perrotta** [comment]
merge

**Pull request merged**
