### PR TITLE
EMTF new LCT coordinate conversion LUTs

### PR DESCRIPTION
**Pull request by abrinke1**
As detailed here [1], the phi coordinates computed in EMTF via the Primitive Conversion Look-Up Tables ("PC LUTs") are significantly displaced from the true coordinates, due to detector mis-alignment effects. EMTF will be loading new PC LUTs reflecting the real CMS geometry, and thus new LUTs and modifications to the emulator are needed to preserve data-emulator agreement.

The emulator changes are being PR-ed separately here: cms-sw/cmssw#24617

This update is urgently needed for the DQM.

Best regards,
Andrew for the EMTF team

[1] https://indico.cern.ch/event/758694/contributions/3146645/subcontributions/263903/attachments/1719883/2776101/2018_09_20_EMTF_alignment.pdf

### CODE REVIEW

**Comment by smuzaffar** [comment]
assign l1
can you please sign it so that we can integrate it?

**Comment by smuzaffar** [comment]
@rekovic,@nsmith-,@thomreis , can you please review and sign it?

**Comment by thomreis** [comment]
+1

**Comment by smuzaffar** [comment]
@mrodozov , can you please prepare a cmsdist PR for this?

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
