### PR TITLE
Adding the golden patterns and hwToLogiclayer in order to trigger displaced muons 

### PR DESCRIPTION
**Pull request by mumuhamm**
Golden Patterns for extrapolated algorithm : Patterns_ExtraplMB1nadMB2SimplifiedFP_t17_classProb17_recalib2_minDP0_v3.xml, 
Hardware to logic layers for Phase-I(run3) : hwToLogicLayer_0x0009.xml
Hardware to logic layers for Phase-II(run4) : hwToLogicLayer_0x0209.xml

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
