### PR TITLE
New PC LUTs for Run 3 2022

### PR DESCRIPTION
**Pull request by eyigitba**
New primitive conversion LUTs for EMTF. 

The LUTs were deployed in firmware on October 6th 2022. These LUTs are necessary for the emulator to replicate firmware behaviour. I will make the relevant PRs to CMSSW shortly.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
This has to go with #39822, which was already merged, and it is needed to read the data taken with the new primitive conversion LUTs in the EMTF emulator, whose firmware was deployed at P5 on October 6th

@eyigitba please confirm that this was tested together with #39822. and provide a few details about how that test was performed.

**Comment by perrotta** [comment]
+1
- See https://github.com/cms-sw/cmssw/pull/39822#issuecomment-1288954321 and https://github.com/cms-sw/cmssw/pull/39822#issuecomment-1288965164

**Comment by perrotta** [comment]
merge
(they are just new files, anyhow)

**Pull request merged**
