### PR TITLE
Updated bmtf_luts/kalmanLUTs.root which was mistakenly added in cmssw

### PR DESCRIPTION
**Pull request by smuzaffar**
The root file was added directory in cmssw via https://github.com/cms-sw/cmssw/pull/33078 . Thsi causing external PR tests to fail ( see https://github.com/cms-sw/cmssw/issues/33303 . This data file should be removed from cmssw

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-data/L1Trigger-L1TMuon#20
- disable_poison = true

**Comment by panoskatsoulis** [comment]
Quick question @smuzaffar.
Is this PR included in the 11_2_4 build that is used for this MWGR?
Or it targets 11_3_X releases only?

FYI @bachtis

**Comment by mrodozov** [comment]
@panoskatsoulis this link
https://github.com/cms-sw/cmsdist/pull/6773
is to the pull request that made this change available in the 11_2 release if the the release was built after this was merged - this change is available in it. In general it's in 11_2

**Comment by panoskatsoulis** [comment]
Thx for the info seems to be included.
The backport PR merged 13 days ago, while the 11_2_4 build created 8 days ago

**Comment by mrodozov** [comment]
so this is it. it's included
`scram list 11_2_4 -> /cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_2_4`
listing this on cvmfs:
`ls /cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_2_4/external/slc7_amd64_gcc900/data/L1Trigger/L1TMuon/data/bmtf_luts`
the file is there for this release -> this data external is including 01-04-00 tag of L1Trigger/L1TMuon :)

**Comment by panoskatsoulis** [comment]
thanks a lot again
this is really helpful
@bachtis the file included in the 11_2_4 release is in here if you want to check
`/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_2_4/external/slc7_amd64_gcc900/data/L1Trigger/L1TMuon/data/bmtf_luts`

**Comment by mrodozov** [comment]
ah the file was there but it's updated :/ hm if it's the same as in 11_3 then checking the old 
du -sh /cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_2_3/external/slc7_amd64_gcc900/data/L1Trigger/L1TMuon/data/bmtf_luts/kalmanLUTs.root
50K	/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_2_3/external/slc7_amd64_gcc900/data/L1Trigger/L1TMuon/data/bmtf_luts/kalmanLUTs.root

and the new one is 227K. So yes it was updated. It's the same (227K) as in the latest IB

**Pull request merged**
